name: video_trimmer_flutter_getx
version: 1.0.0+1
publish_to: none
description: Video Trimmer Demo
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  video_trimmer: ^1.1.3
  file_picker: ^4.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
